sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
script:
  - npm run app:test
after_success:
  - npm run deploy
after_script:
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
deploy:
  local_dir: build
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master