sudo: false
language: node_js
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
after_success:
  - npm run web:build
after_script:
  - greenkeeper-lockfile-upload
branches:
  only:
    - master
deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master